apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  PGDATA: /var/lib/postgresql/data/pgdata
  REDMINE_DB_POSTGRES: database
  REDMINE_DB_USERNAME: testuser
  REDMINE_DB_DATABASE: testdatabase

