apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3JkCg==
  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXk=
  REDMINE_DB_PASSWORD: dGVzdHBhc3N3b3JkCg==
